### ISSUE TITLE
Upgrading Ubuntu

### ISSUE THREAD

**Issue by jonk999** [mrin/domoticz-mirobot-plugin#11]
I was running the plugin fine on Ubuntu 16.04.
I upgraded to 17.10 due to needing a higher version of Python for another app.
I went through the setup process again as I believe Python is now 3.6.
When I run the test.py I get the following:
domoticz@Domoticz:~/domoticz/plugins/xiaomi-mirobot$ sudo ./test.py
test: python modules path: ././.env/lib/python3.6/site-packages
test: python modules path: ././.env/lib/python3.5/site-packages
test: trying connect to 127.0.0.1:22222
Traceback (most recent call last):
  File "./test.py", line 22, in <module>
    client = socket.create_connection((args.host, args.port))
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
domoticz@Domoticz:~/domoticz/plugins/xiaomi-mirobot$

Is someone able to assist?

**Comment by alexunderboots** [comment]
I have the same problem on ubunta 18.04 server. please help
