### ISSUE TITLE
Installation broken on raspbian Buster

### ISSUE THREAD

**Issue by dobber81** [mrin/domoticz-mirobot-plugin#19]
During installation there are lots of errors when using Rpi4 and Buster.

After this:
Building wheels for collected packages: gevent, msgpack-python, greenlet
  Building wheel for gevent (setup.py) ... \

Tried both pip3 install -r pip_req.txt and pip3 install gevent msgpack-python python-miio==0.3.1

End result is crash and burn. Installation does not work.

**Comment by TerrorSource** [comment]
It's not broken. mirobot depens on a particular version of pip packages, which are updated in the meanwhile.

Try doing the following steps:
1. Follow the manual via https://github.com/mrin/domoticz-mirobot-plugin and STOP before running "pip3 install -r pip_req.txt"
2. Edit pip_req.txt and change the following, save when done.
pip3 install gevent==1.2.2
change version to: 1.4.0

pip3 install greenlet==0.4.12
change version to: 0.4.15

3. Continue with the manual.

Works for me on a Pi 4 with Buster.

**Comment by albebert** [comment]
changed gevent to 1.4.0 and greenlet to 0.4.12

dependencies are ok but serveur reports errors :



`(.env) root@domoticzx64:/opt/domoticz/plugins/xiaomi-mirobot# /opt/domoticz/plugins/xiaomi-mirobot/miio_server.py -- 192.168.***.*** ********************** --host 127.0.0.1 --port 22222
Traceback (most recent call last):
  File "/opt/domoticz/plugins/xiaomi-mirobot/miio_server.py", line 9, in <module>
    from gevent import monkey
  File "/opt/domoticz/plugins/xiaomi-mirobot/./.env/lib/python3.7/site-packages/gevent/__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
  File "/opt/domoticz/plugins/xiaomi-mirobot/./.env/lib/python3.7/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/opt/domoticz/plugins/xiaomi-mirobot/./.env/lib/python3.7/site-packages/gevent/_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/__greenlet_primitives.pxd", line 12, in init gevent.__hub_local
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 144 from PyObject
`
