### ISSUE TITLE
Script problem after uptdate python

### ISSUE THREAD

**Issue by xAsKeYx** [mrin/domoticz-mirobot-plugin#25]
Hello,

I have update python 3.5 to 3.7, i follow again the instruction for install it and i have this error :

(.env) root@srv-askey:/opt/domoticz/plugins/xiaomi-mirobot# ./miio_server.py 192.168.1.42 "******************************************" --host 127.0.0.1 --port 22222
Traceback (most recent call last):
  File "./miio_server.py", line 17, in <module>
    from miio import Vacuum, DeviceException
  File "/usr/local/lib/python3.7/site-packages/miio/__init__.py", line 2, in <module>
    from miio.airconditioningcompanion import (
  File "/usr/local/lib/python3.7/site-packages/miio/airconditioningcompanion.py", line 8, in <module>
    from .device import Device, DeviceException
  File "/usr/local/lib/python3.7/site-packages/miio/device.py", line 14, in <module>
    from .protocol import Message
  File "/usr/local/lib/python3.7/site-packages/miio/protocol.py", line 206, in <module>
    Const(0x2131, Int16ub),
  File "/usr/local/lib/python3.7/site-packages/construct/core.py", line 1930, in __init__
    super(Const, self).__init__(subcon)
  File "/usr/local/lib/python3.7/site-packages/construct/core.py", line 288, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field

Regards

**Comment by Sateetje** [comment]
Same problem here:

Traceback (most recent call last):
  File "./miio_server.py", line 17, in <module>
    from miio import Vacuum, DeviceException
  File "/usr/local/lib/python3.7/dist-packages/miio/__init__.py", line 2, in <module>
    from miio.protocol import Message, Utils
  File "/usr/local/lib/python3.7/dist-packages/miio/protocol.py", line 155, in <module>
    Const(Int16ub, 0x2131),
  File "/usr/local/lib/python3.7/dist-packages/construct/core.py", line 2504, in __init__
    super(Const, self).__init__(subcon)
  File "/usr/local/lib/python3.7/dist-packages/construct/core.py", line 670, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field

**Comment by xAsKeYx** [comment]
my plugin working : 
I solve my problem with 
https://ehoco.nl/roborock-vacuum-cleaner-bedienen-domoticz/
and https://github.com/mrin/domoticz-mirobot-plugin

**Comment by Sateetje** [comment]
With version 3.7 of python?

**Comment by Sateetje** [comment]
This did the trick: python-miio==0.4.5

This problem was solved in v0.3.5, pip installs v0.3.1 by default

**Comment by AlexCoursi** [comment]
I used the following versions in pip_req.txt

	gevent==1.4.0
	greenlet==0.4.15
	python-miio==0.4.5
	attrs==17.4.0
	construct==2.10.56
