### ISSUE TITLE
Stopped working after Ubuntu upgrade

### ISSUE THREAD

**Issue by DarkAllMan** [mrin/domoticz-mirobot-plugin#34]
Noobs here....
But after updating my ubuntu version, it all stopped working:
`Traceback (most recent call last):
  File "./miio_server.py", line 9, in <module>
    from gevent import monkey
  File "././.env/lib/python3.6/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "././.env/lib/python3.6/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "././.env/lib/python3.6/site-packages/gevent/_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'
`

Can anyone point me in the right direction? I see python 3.6 mentioned, but my current system has 3.8.5?

**Comment by Tontze** [comment]
I have similar problem with new debian install .. 

` sudo ./miio_server.py 192.168.1.24 75566839764d74326b36727252594c62 --host 127.0.0.1 --port 22222
Traceback (most recent call last):
  File "/home/tontze/domoticz/plugins/xiaomi-mirobot/./miio_server.py", line 17, in <module>
    from miio import Vacuum, DeviceException
  File "/home/tontze/domoticz/plugins/xiaomi-mirobot/././.env/lib/python3.9/site-packages/miio/__init__.py", line 2, in <module>
    from miio.protocol import Message, Utils
  File "/home/tontze/domoticz/plugins/xiaomi-mirobot/././.env/lib/python3.9/site-packages/miio/protocol.py", line 155, in <module>
    Const(Int16ub, 0x2131),
  File "/home/tontze/domoticz/plugins/xiaomi-mirobot/././.env/lib/python3.9/site-packages/construct/core.py", line 2537, in __init__
    super(Const, self).__init__(subcon)
  File "/home/tontze/domoticz/plugins/xiaomi-mirobot/././.env/lib/python3.9/site-packages/construct/core.py", line 673, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field
`
