### ISSUE TITLE
 TypeError("subcon should be a Construct field")

### ISSUE THREAD

**Issue by Tontze** [mrin/domoticz-mirobot-plugin#35]
I have this problem in new debian install : 

`tontze@T610:~/domoticz/plugins/xiaomi-mirobot$ sudo ./miio_server.py 192.168.1.24 xxxxxxxxxxxxxxxxxxxxxxxxxxxx --host 127.0.0.1 --port 22222
Traceback (most recent call last):
  File "/home/tontze/domoticz/plugins/xiaomi-mirobot/./miio_server.py", line 17, in <module>
    from miio import Vacuum, DeviceException
  File "/home/tontze/domoticz/plugins/xiaomi-mirobot/././.env/lib/python3.9/site-packages/miio/__init__.py", line 2, in <module>
    from miio.protocol import Message, Utils
  File "/home/tontze/domoticz/plugins/xiaomi-mirobot/././.env/lib/python3.9/site-packages/miio/protocol.py", line 155, in <module>
    Const(Int16ub, 0x2131),
  File "/home/tontze/domoticz/plugins/xiaomi-mirobot/././.env/lib/python3.9/site-packages/construct/core.py", line 2537, in __init__
    super(Const, self).__init__(subcon)
  File "/home/tontze/domoticz/plugins/xiaomi-mirobot/././.env/lib/python3.9/site-packages/construct/core.py", line 673, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field
`

Debian 11 bullseye
construct-2.10.61

**Comment by Bartras** [comment]
Same for me...

**Comment by Tontze** [comment]
As this was installed through https://github.com/mrin/domoticz-mirobot-plugin it had old version or something, i got it working by : 

`sudo pip3 install python-miio`
