### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by tomgue76** [mrin/domoticz-mirobot-plugin#39]
Hi,

i try to install it since a couple of day and always i got sale errors.

1. When i try to install gevent, msgpack and greenlet i have wheel errors => i try to change versions it seems install is ok but it don't work when  i try to launch test.py i got issue
`test: python modules path: /home/tg76/domoticz/plugins/xiaomi-mirobot/././.env/lib/python3.9/site-packages
test: trying connect to 127.0.0.1:22222
Traceback (most recent call last):
  File "/home/tg76/domoticz/plugins/xiaomi-mirobot/./test.py", line 22, in <module>
    client = socket.create_connection((args.host, args.port))
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused`

is somebody can help me to install it. python 3.9 is the problem?

rpi 4 64bits bullseye
python 3.9

thanks a lot

**Comment by cth35** [comment]
May be try to update the pip_req.txt with : 

android-backup==0.1.0
asn1crypto==0.23.0
attrs==23.2.0
cffi==1.15.1
click==8.1.7
construct==2.10.68
cryptography==37.0.2
enum-compat==0.0.2
gevent==1.4.0
greenlet==0.4.15
idna==2.6
msgpack-python==0.4.8
netifaces==0.11.0
pretty-cron==1.0.2
pycparser==2.21
pycrypto==2.6.1
python-miio==0.5.12
pytz==2017.3
six==1.11.0
typing==3.6.2
zeroconf==0.131.0

And restart the server.
